stages:
  - build
  - test
  - notify
  - deploy

variables:
  IMAGE: orvice/mu-sync

build:bin:
  stage: build
  image: golang
  script:
    - go mod download
    - make build

build:docker:
  stage: build
  image: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/$IMAGE:latest .
    - docker push $CI_REGISTRY/$IMAGE:latest

test:
  stage: test
  image: golang
  allow_failure: true
  script:
    - go test -v ./...

