image: docker:latest
services:
  - docker:dind
stages:
  - build
  - test
  - notify
  - deploy

build:bin:
  stage: build
  image: golang
  script:
    - go mod download
    - make build

build:docker:
  stage: build
  image: docker
  script:
    - export IMAGE_TAG=$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-')
    - docker login -u "$CI_BUILD_USER"  -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    - docker tag "$CI_REGISTRY_IMAGE:$IMAGE_TAG" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"

test:
  stage: test
  image: golang
  allow_failure: true
  script:
    - go test -v ./...

